/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const sidebars = {
  // But you can create a sidebar manually
  tokengatedSidebar: [
    "tokengated-polkadot-next-js/intro",
    "tokengated-polkadot-next-js/step2",
    "tokengated-polkadot-next-js/conclusion",
  ],

  substrateInBitsSidebar: [
    {
      type: "category",
      label: "Substrate in Bits",
      link: {
        type: "tutorial",
        id: "substrate-in-bits/README",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "substrate-in-bits/docs",
        },
      ],
    },
  ],

  // add a sidebar for your tutorial here like
  // yourTutorialSidebar: [
  //  {
  //    type: "category",
  //    label: "Your Tutorial Title",
  //    items: ["your-tutorial-folder/intro", <...other items >],
  //  },
};

module.exports = sidebars;
