/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const sidebars = {
  // But you can create a sidebar manually

  tokengatedSidebar: [
    "tokengated-polkadot-next-js/intro",
    "tokengated-polkadot-next-js/step2",
    "tokengated-polkadot-next-js/conclusion",
  ],
  
  substrateInBitsSidebar: [
    {
      type: "category",
      label: "Substrate in Bits",
      link: {
        type: "tutorial",
        id: "substrate-in-bits/README",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "substrate-in-bits/docs",
        },
      ],
    },
  ],

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Basic Wallet with Polkadot-js and React with Typescript',
      items: [
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/intro',
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/step1',
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/step2',
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/step3',
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/step4',
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/step5',
          'tutorials/wallet-with-polkadot-js-and-react-with-typescript/conclusion'
      ],
  },
  ],
};

module.exports = sidebars;
